--03_stage_file_format_copy.sql

USE DATABASE ECOMERSE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE TD_ORDERS_STAGE;

CREATE OR REPLACE FILE FORMAT TD_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

COPY INTO TD_ORDERS_RAW
FROM @TD_ORDERS_STAGE
FILE_FORMAT = (FORMAT_NAME = TD_CSV_FORMAT)
ON_ERROR = 'CONTINUE';
