-- 06_quality_checks.sql
-- Проверки след изпълнение на скриптовете.

USE DATABASE ECOMERSE_DB;
USE SCHEMA RAW;

SELECT 'RAW_RECORDS' AS CHECK_NAME, COUNT(*) AS RECORD_COUNT FROM TD_ORDERS_RAW
UNION ALL
SELECT 'FOR_REVIEW_DELIVERED_WITHOUT_ADDRESS', COUNT(*) FROM TD_FOR_REVIEW
UNION ALL
SELECT 'SUSPICIOUS_MISSING_CUSTOMER_ID', COUNT(*) FROM TD_SUSPICIOUS_RECORDS
UNION ALL
SELECT 'INVALID_DATE_FORMAT', COUNT(*) FROM TD_INVALID_DATE_FORMAT
UNION ALL
SELECT 'INVALID_QUANTITY_PRICE', COUNT(*) FROM TD_INVALID_QUANTITY_PRICE
UNION ALL
SELECT 'CLEAN_RECORDS', COUNT(*) FROM TD_CLEAN_RECORDS;

-- Проверка за липсващ Payment_Method във финалната таблица
SELECT COUNT(*) AS MISSING_PAYMENT_METHODS
FROM TD_CLEAN_RECORDS
WHERE Payment_Method IS NULL OR TRIM(Payment_Method) = '';

-- Проверка за невалидни отстъпки във финалната таблица
SELECT COUNT(*) AS INVALID_DISCOUNTS
FROM TD_CLEAN_RECORDS
WHERE Discount < 0 OR Discount > 0.50;

-- Проверка за невалидни количества/цени във финалната таблица
SELECT COUNT(*) AS INVALID_QUANTITY_OR_PRICE
FROM TD_CLEAN_RECORDS
WHERE Quantity <= 0 OR Price <= 0;

-- Проверка за грешно калкулирана крайна цена
SELECT COUNT(*) AS WRONG_TOTAL_AMOUNT
FROM TD_CLEAN_RECORDS
WHERE Total_Amount <> ROUND(Quantity * Price * (1 - Discount), 2);

-- Проверка за Delivered без адрес
SELECT COUNT(*) AS DELIVERED_WITHOUT_ADDRESS
FROM TD_CLEAN_RECORDS
WHERE UPPER(Status) = 'DELIVERED'
  AND Shipping_Address IS NULL;
